// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuasarWebAppAPI.EFCore;

#nullable disable

namespace QuasarWebAppAPI.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    partial class EF_DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.blendflag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("blendFlag_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("blendFlag_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("blendFlag_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("blendFlag_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("blendFlag_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("blendFlag_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("blendFlag_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("blendFlag_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("blendFlag_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("blendFlag_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("blendFlag_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("blendFlag_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("blendFlag_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("blendFlag_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("blendFlag_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("blendFlag_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("blendFlag_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("blendFlag_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("blendFlag_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("blendFlag_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("blendFlag_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("blendFlag_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("blendFlag_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("blendFlag_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("blendFlag_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("blendFlag_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("blendFlag_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("blendFlag_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("blendFlag_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("blendFlag_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("blendFlag_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.Property<float>("dblendFlag_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.HasKey("id");

                    b.ToTable("blendflag");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.deltav_sys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("deltavSys_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("deltavSys_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("deltavSys_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("deltavSys_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("deltavSys_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("deltavSys_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("deltavSys_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("deltavSys_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("deltavSys_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("deltavSys_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("deltavSys_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("deltavSys_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("deltavSys_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("deltavSys_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("deltavSys_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("deltavSys_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("deltavSys_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("deltavSys_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("deltavSys_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("deltavSys_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("deltavSys_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("deltavSys_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("deltavSys_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("deltavSys_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("deltavSys_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("deltavSys_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("deltavSys_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("deltavSys_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("deltavSys_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("deltavSys_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("deltavSys_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("deltavSys_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("deltav_sys");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.deltaz_sys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("deltazSys_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("deltazSys_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("deltazSys_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("deltazSys_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("deltazSys_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("deltazSys_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("deltazSys_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("deltazSys_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("deltazSys_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("deltazSys_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("deltazSys_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("deltazSys_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("deltazSys_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("deltazSys_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("deltazSys_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("deltazSys_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("deltazSys_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("deltazSys_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("deltazSys_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("deltazSys_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("deltazSys_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("deltazSys_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("deltazSys_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("deltazSys_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("deltazSys_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("deltazSys_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("deltazSys_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("deltazSys_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("deltazSys_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("deltazSys_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("deltazSys_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("deltazSys_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("deltaz_sys");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.ew_err_obs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("eErrObs_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("eErrObs_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("eErrObs_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("eErrObs_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("eErrObs_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("eErrObs_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("eErrObs_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("eErrObs_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("eErrObs_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("eErrObs_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("eErrObs_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("eErrObs_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("eErrObs_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("eErrObs_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("eErrObs_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("eErrObs_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("eErrObs_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("eErrObs_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("eErrObs_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("eErrObs_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("eErrObs_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("eErrObs_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("eErrObs_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("eErrObs_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("eErrObs_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("eErrObs_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("eErrObs_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("eErrObs_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("eErrObs_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("eErrObs_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("eErrObs_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("eErrObs_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("ew_err_obs");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.ew_obs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("eObs_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("eObs_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("eObs_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("eObs_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("eObs_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("eObs_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("eObs_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("eObs_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("eObs_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("eObs_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("eObs_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("eObs_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("eObs_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("eObs_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("eObs_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("eObs_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("eObs_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("eObs_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("eObs_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("eObs_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("eObs_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("eObs_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("eObs_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("eObs_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("eObs_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("eObs_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("eObs_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("eObs_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("eObs_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("eObs_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("eObs_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("eObs_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("ew_obs");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.fwhm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("fwhm_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("fwhm_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("fwhm_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("fwhm_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("fwhm_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("fwhm_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("fwhm_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("fwhm_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("fwhm_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("fwhm_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("fwhm_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("fwhm_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("fwhm_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("fwhm_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("fwhm_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("fwhm_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("fwhm_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("fwhm_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("fwhm_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("fwhm_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("fwhm_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("fwhm_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("fwhm_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("fwhm_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("fwhm_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("fwhm_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("fwhm_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("fwhm_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("fwhm_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("fwhm_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("fwhm_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("fwhm_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("fwhm");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.gradeflag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("gradeFlag_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("gradeFlag_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("gradeFlag_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("gradeFlag_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("gradeFlag_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("gradeFlag_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("gradeFlag_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("gradeFlag_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("gradeFlag_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("gradeFlag_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("gradeFlag_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("gradeFlag_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("gradeFlag_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("gradeFlag_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("gradeFlag_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("gradeFlag_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("gradeFlag_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("gradeFlag_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("gradeFlag_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("gradeFlag_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("gradeFlag_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("gradeFlag_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("gradeFlag_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("gradeFlag_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("gradeFlag_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("gradeFlag_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("gradeFlag_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("gradeFlag_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("gradeFlag_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("gradeFlag_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("gradeFlag_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("gradeFlag_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("gradeflag");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.lambda_obs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("lObs_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("lObs_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("lObs_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("lObs_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("lObs_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("lObs_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("lObs_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("lObs_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("lObs_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("lObs_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("lObs_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("lObs_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("lObs_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("lObs_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("lObs_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("lObs_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("lObs_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("lObs_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("lObs_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("lObs_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("lObs_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("lObs_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("lObs_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("lObs_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("lObs_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("lObs_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("lObs_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("lObs_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("lObs_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("lObs_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("lObs_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("lObs_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("lambda_obs");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.lambda_vac", b =>
                {
                    b.Property<float>("lVac_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("lVac_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("lVac_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("lVac_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("lVac_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("lVac_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("lVac_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("lVac_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("lVac_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("lVac_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("lVac_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("lVac_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("lVac_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("lVac_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("lVac_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("lVac_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("lVac_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("lVac_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("lVac_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("lVac_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("lVac_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("lVac_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("lVac_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("lVac_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("lVac_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("lVac_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("lVac_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("lVac_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("lVac_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("lVac_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("lVac_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("lVac_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.ToTable("lambda_vac");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.lya_flag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("lyFlag_1025")
                        .HasColumnType("real")
                        .HasColumnName("1025.7");

                    b.Property<float>("lyFlag_1215")
                        .HasColumnType("real")
                        .HasColumnName("1215.7");

                    b.Property<float>("lyFlag_1238")
                        .HasColumnType("real")
                        .HasColumnName("1238.8");

                    b.Property<float>("lyFlag_1260")
                        .HasColumnType("real")
                        .HasColumnName("1260.4");

                    b.Property<float>("lyFlag_1302")
                        .HasColumnType("real")
                        .HasColumnName("1302.2");

                    b.Property<float>("lyFlag_1304")
                        .HasColumnType("real")
                        .HasColumnName("1304.4");

                    b.Property<float>("lyFlag_1334")
                        .HasColumnType("real")
                        .HasColumnName("1334.5");

                    b.Property<float>("lyFlag_1393")
                        .HasColumnType("real")
                        .HasColumnName("1393.8");

                    b.Property<float>("lyFlag_1402")
                        .HasColumnType("real")
                        .HasColumnName("1402.8");

                    b.Property<float>("lyFlag_1526")
                        .HasColumnType("real")
                        .HasColumnName("1526.7");

                    b.Property<float>("lyFlag_1548")
                        .HasColumnType("real")
                        .HasColumnName("1548.2");

                    b.Property<float>("lyFlag_1550")
                        .HasColumnType("real")
                        .HasColumnName("1550.8");

                    b.Property<float>("lyFlag_1608")
                        .HasColumnType("real")
                        .HasColumnName("1608.5");

                    b.Property<float>("lyFlag_1656")
                        .HasColumnType("real")
                        .HasColumnName("1656.9");

                    b.Property<float>("lyFlag_1670")
                        .HasColumnType("real")
                        .HasColumnName("1670.8");

                    b.Property<float>("lyFlag_1854")
                        .HasColumnType("real")
                        .HasColumnName("1854.7");

                    b.Property<float>("lyFlag_1862")
                        .HasColumnType("real")
                        .HasColumnName("1862.8");

                    b.Property<float>("lyFlag_2026")
                        .HasColumnType("real")
                        .HasColumnName("2026.1");

                    b.Property<float>("lyFlag_2056")
                        .HasColumnType("real")
                        .HasColumnName("2056.3");

                    b.Property<float>("lyFlag_2260")
                        .HasColumnType("real")
                        .HasColumnName("2260.8");

                    b.Property<float>("lyFlag_2374")
                        .HasColumnType("real")
                        .HasColumnName("2374.5");

                    b.Property<float>("lyFlag_2382")
                        .HasColumnType("real")
                        .HasColumnName("2382.8");

                    b.Property<float>("lyFlag_2586")
                        .HasColumnType("real")
                        .HasColumnName("2586.7");

                    b.Property<float>("lyFlag_2594")
                        .HasColumnType("real")
                        .HasColumnName("2594.5");

                    b.Property<float>("lyFlag_2600")
                        .HasColumnType("real")
                        .HasColumnName("2600.2");

                    b.Property<float>("lyFlag_2796")
                        .HasColumnType("real")
                        .HasColumnName("2796.4");

                    b.Property<float>("lyFlag_2803")
                        .HasColumnType("real")
                        .HasColumnName("2803.5");

                    b.Property<float>("lyFlag_2853")
                        .HasColumnType("real")
                        .HasColumnName("2853.0");

                    b.Property<float>("lyFlag_3242")
                        .HasColumnType("real")
                        .HasColumnName("3242.9");

                    b.Property<float>("lyFlag_3934")
                        .HasColumnType("real")
                        .HasColumnName("3934.8");

                    b.Property<float>("lyFlag_3969")
                        .HasColumnType("real")
                        .HasColumnName("3969.6");

                    b.Property<float>("lyFlag_5891")
                        .HasColumnType("real")
                        .HasColumnName("5891.5");

                    b.HasKey("id");

                    b.ToTable("lya_flag");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.quasar_catalog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("_20cm_flux")
                        .HasColumnType("real")
                        .HasColumnName("20cm_flux");

                    b.Property<float>("_20cm_snr")
                        .HasColumnType("real")
                        .HasColumnName("20cm_snr");

                    b.Property<float>("avesnr_spec")
                        .HasColumnType("real");

                    b.Property<int>("bal_flag")
                        .HasColumnType("integer");

                    b.Property<int>("bal_flag2")
                        .HasColumnType("integer");

                    b.Property<float>("beta")
                        .HasColumnType("real");

                    b.Property<float>("civ_class_score")
                        .HasColumnType("real");

                    b.Property<float>("dec_deg")
                        .HasColumnType("real");

                    b.Property<float>("dec_hex")
                        .HasColumnType("real");

                    b.Property<float>("dla_flag_nd2013")
                        .HasColumnType("real");

                    b.Property<float>("dla_lognhi_nd2013")
                        .HasColumnType("real");

                    b.Property<float>("dla_zabs_nd2013")
                        .HasColumnType("real");

                    b.Property<int>("fiber")
                        .HasColumnType("integer");

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("iabmag")
                        .HasColumnType("real");

                    b.Property<float>("imag")
                        .HasColumnType("real");

                    b.Property<float>("mgii_class_score")
                        .HasColumnType("real");

                    b.Property<int>("mjd")
                        .HasColumnType("integer");

                    b.Property<int>("num_5sigma_unided_inlya")
                        .HasColumnType("integer");

                    b.Property<int>("num_5sigma_unided_notinlya")
                        .HasColumnType("integer");

                    b.Property<float>("other_class_score")
                        .HasColumnType("real");

                    b.Property<int>("plate")
                        .HasColumnType("integer");

                    b.Property<float>("ra_deg")
                        .HasColumnType("real");

                    b.Property<float>("ra_hex")
                        .HasColumnType("real");

                    b.Property<string>("run_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("sep_first")
                        .HasColumnType("real");

                    b.Property<float>("spec_avesnr")
                        .HasColumnType("real");

                    b.Property<float>("spec_avesnr_red")
                        .HasColumnType("real");

                    b.Property<float>("spec_medsnr")
                        .HasColumnType("real");

                    b.Property<float>("spec_medsnr_red")
                        .HasColumnType("real");

                    b.Property<int>("sys_num")
                        .HasColumnType("integer");

                    b.Property<int>("target_first")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("z_abs")
                        .HasColumnType("real");

                    b.Property<float>("z_fgal")
                        .HasColumnType("real");

                    b.Property<float>("z_qso")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("quasar_catalog");
                });

            modelBuilder.Entity("QuasarWebAppAPI.EFCore.w_limits", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("col0")
                        .HasColumnType("real");

                    b.Property<float>("col1")
                        .HasColumnType("real");

                    b.Property<float>("col2")
                        .HasColumnType("real");

                    b.Property<float>("col3")
                        .HasColumnType("real");

                    b.Property<float>("col4")
                        .HasColumnType("real");

                    b.Property<float>("col5")
                        .HasColumnType("real");

                    b.Property<float>("col6")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("w_limits");
                });
#pragma warning restore 612, 618
        }
    }
}
